[tool.poetry]
name = "budget"
version = "0.0.1"
authors = ["Alexander Kuhn-Regnier"]
description = "Analyse budgeting info"

[tool.poetry.dependencies]
python = "^3.11.4"
numpy = "*"
scipy = "*"
matplotlib = "*"
pandas = "*"
ipython = "*"
ipdb = "*"

[tool.ruff]
target-version = "py311"
